defaults: &defaults
  adapter:  mysql
  database: rankey_development
  username: root
  password: 
  host:     localhost

development:
  <<: *defaults

test:
  database: rankey_test
  <<: *defaults

travis:
  database: rankey_test
  username:
  <<: *defaults

production:
  database: rankey_production
  password: secret
  <<: *defaults
